services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    environment:
      - FLASK_ENV=development
    image: development:latest 
  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"